apiVersion: v1
kind: Service
metadata:
  name: scharp-microservice-service
spec:
  selector:
    app: scharp-microservice
  ports:
    - protocol: TCP
      port: 5074
      targetPort: 5074
      nodePort: 32001
  type: NodePort
